# Site settings
title: haofp                # 你的博客网站标题
SEOTitle: My Blog           # 在后面会详细谈到
description: "Hey This is my blog , welcome!"    # 随便说点，描述一下

# SNS settings      
github_username: haofp      # 你的github账号
weibo_username: haofp    # 你的微博账号，底部链接会自动更新的。

# Build settings
# paginate: 10              # 一页你准备放几篇文章
